user = "thatscotdatasci"
project = "terraform-lambda"
environment = "dev"

github_owner = "thatscotdatasci"
github_repo = "aws-lambda-hello-world"
github_project_url = "https://github.com/thatscotdatasci/aws-lambda-hello-world.git"
github_branch = "master"

kms_alias = "kms"
s3_lambda_code_bucket_name = "lambda-code"
codebuild_iam_role_name = "codebuild-iam-role"
codebuild_project_name = "codebuild-project"
codebuild_artifact_name = "artifact"
codepipeline_name = "codepipeline"
